services:
  db:
    image: postgres:15
    container_name: jamrik_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    container_name: jamrik_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_AI_GOOGLE_AI_API_KEY=${SPRING_AI_GOOGLE_AI_API_KEY}

  frontend:
   image: ahmeddyasien/jamrik_frontend
   container_name: jamrik_frontend
   ports:
     - "3000:80"
     - "80:80"
   volumes:
    - ../frontend/out:/usr/share/nginx/html

volumes:
  postgres_data: