spring.application.name=jamrik

# Database Connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://jamrik_db:5432/jamrik}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings (creates tables automatically)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=mappings
#AI configs
#enable the Google GenAI Chat Model
spring.ai.model.chat.google-genai.enabled=true
#Setting the Model
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.api-version=v1
spring.ai.google.genai.api-key=${SPRING_AI_GOOGLE_AI_API_KEY}
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
#Security details
spring.security.user.name=admin
spring.security.user.password=jamrik26
# File Upload Limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
